### ISSUE TITLE
Merge with other the omniauth strategy

### ISSUE THREAD

**Issue by derrickreimer** [DripEmail/omniauth-drip#1]
Hey @podman! CTO of Drip here, glad to see you folks integrating with us! As chance would have it, @j-mcnally created an Omniauth strategy for Drip the same day as you. When we went to rename his gem from `omniauth-getdrip` to `omniauth-drip`, we discovered your gem: waitlisted/omniauth-drip#1

I'd like to link out to an Omniauth strategy from our official API docs, and ideally there would be one official source for this. Would you be willing to merge efforts with @j-mcnally?

I'd be happy to place the official source under the DripEmail organization, credit both of you for your work there, and help maintain it.

**Comment by podman** [comment]
Hi, @djreimer! I'm happy to do whatever is easiest. I can transfer ownership to DripEmail and then you guys can do whatever you'd like. Is that the ideal outcome as you see it?

**Comment by j-mcnally** [comment]
I'd say we can merge efforts from a code perspective you actually have
tests so id be in favor of using yours as a base.

On Wednesday, July 22, 2015, Adam Podolnick notifications@github.com
wrote:

> Hi, @djreimer https://github.com/djreimer! I'm happy to do whatever is
> easiest. I can transfer ownership to DripEmail and then you guys can do
> whatever you'd like. Is that the ideal outcome as you see it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SproutVideo/omniauth-drip/issues/1#issuecomment-123794177
> .

## 

http://www.kohactive.com
Justin McNally
Technology Director / Principal
p: 312.273.3074 <+13122733074> | e: justin@kohactive.com | skype:
justinmcnally211 http://is.gd/UuXAGG
  https://github.com/j-mcnally  https://twitter.com/j_mcnally
https://www.linkedin.com/profile/view?id=143776726

**Comment by derrickreimer** [comment]
Great! @podman that would we probably be the easiest way to go. Also, could you add me as a gem owner on Rubygems? Email address is derrickreimer at gmail.

**Comment by podman** [comment]
@djreimer OK, you're now added as an owner for the gem. I'm about to transfer ownership of the repository to DripEmail.

**Comment by podman** [comment]
@djreimer I got the following error when trying to transfer the repository: You don’t have admin rights to DripEmail.

I guess I can transfer it directly to you first and then you can transfer it to the organization?

**Comment by derrickreimer** [comment]
@podman interesting, yeah that should work

**Comment by podman** [comment]
@djreimer Looks like this is all set now. Let me know if I can do anything else to help.

**Comment by timbreitkreutz** [comment]
Merged and tested.  Prepping a 0.0.2 release.
